In [1]:
#Implement the different Distance methods (Euclidean) with Prediction, Test Score and Confusion Matrix
#Import required libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [3]:
#Load the dataset
df = pd.read_csv("E:/Downloads/IRIS.csv")

In [4]:
#quick look into the data
df.head(5)

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [5]:
#Separate data and label
x = df.drop(['species'], axis=1)
y = df['species']


In [6]:
#Prepare data for classification process
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

In [7]:
#Create a model , p = 2 => Euclidean Distance:
knn = KNeighborsClassifier(n_neighbors = 6, p = 2, metric='minkowski')

In [8]:
#Train the model
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=6)

In [9]:
# Calculate the accuracy of the model
print(knn.score(x_test, y_test))
y_pred = knn.predict(x_test)

0.9777777777777777


In [10]:
#confusion matrix 
from sklearn.metrics import  confusion_matrix
cm=np.array(confusion_matrix(y_test,y_pred))
cm


array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]], dtype=int64)

In [11]:
#Create a model , p = 1 => Manhattan Distance
knn = KNeighborsClassifier(n_neighbors = 6, p = 1, metric='minkowski')

In [12]:
#Train the model
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=6, p=1)

In [13]:
# Calculate the accuracy of the model
print(knn.score(x_test, y_test))
y_pred = knn.predict(x_test)

0.9555555555555556


In [14]:
#confusion matrix 
from sklearn.metrics import  confusion_matrix
cm=np.array(confusion_matrix(y_test,y_pred))
cm

array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  1, 10]], dtype=int64)

In [15]:
#Create a model ,p = ∞, Chebychev Distance
#let ∞ = 10000
knn = KNeighborsClassifier(n_neighbors = 6, p = 10000, metric='minkowski')

In [16]:
#Train the model
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=6, p=10000)

In [17]:
# Calculate the accuracy of the model
print(knn.score(x_test, y_test))
y_pred = knn.predict(x_test)

0.8


In [18]:
#confusion matrix 
from sklearn.metrics import  confusion_matrix
cm=np.array(confusion_matrix(y_test,y_pred))
cm

array([[16,  0,  0],
       [ 0, 18,  0],
       [ 0,  9,  2]], dtype=int64)